# Server Configuration
server.port=8086

# Application Name
spring.application.name=sla-microservice

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/dxc_form?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Root@123

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS
spring.web.cors.allowed-origins=*

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moememboughanmi@gmail.com
spring.mail.password=rlhhepvctqoqqqhz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# RH email for notifications & copies
app.hr.email=aminaboughanmi34@gmail.com

# JWT
app.jwt.secret=ZHhjLXNlY3JldC1rZXktY2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbi13aXRoLWEtdmVyeS1sb25nLXJhbmRvbS1zdHJpbmc=

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
