
server.port=8083
spring.application.name=auth-microservice

spring.datasource.url=jdbc:mysql://localhost:3306/dxc_form?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moememboughanmi@gmail.com
spring.mail.password=rlhhepvctqoqqqhz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.email.from=noreply@dxc.com
app.email.from-name=DXC Technology

app.jwt.secret=ZHhjLXNlY3JldC1rZXktY2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbi13aXRoLWEtdmVyeS1sb25nLXJhbmRvbS1zdHJpbmc=
app.jwt.expiration-ms=86400000

app.otp.length=6
app.otp.expiration-minutes=5


app.verification.expiration-hours=24


app.frontend.url=file:///C:/Users/Moemen/Documents/DXC_Projet/dxc-final/dxc-frontend


logging.level.com.dxc.auth=DEBUG
logging.level.org.springframework.mail=DEBUG
